#!/usr/bin/env python

import sys

from arm_package.m2_1_module import M2_motor1
from rqt_gui.main import Main

plugin = 'm2_motor1_pkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
