#!/usr/bin/env python

import sys

from arm_package.m2_2_module import M2_motor2
from rqt_gui.main import Main

plugin = 'm2_motor2_pkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
