#!/usr/bin/env python

import sys

from arm_package.m3_module import MyPlugin
from rqt_gui.main import Main

plugin = 'm3_motor_pkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
